<section class="bloc-intro">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 mt-5 mb-5 text-center">
                <h1>Toutes les Ô Tartes</h1>
                <!-- faire foreach voir ex hoempage smoothmaker-->
                <img src="assets/img/<?=$allPies['image']?>" alt="<?=$allPies['alt']?>" class="img-responsive fit-image">
                <div class="box box-small">
                    <h4><?=$allPies['name']?></h4>
                </div>
                <!--  -->
            </div>
        </div>
    </div>
</section>



