<section class="container upload">
    <h2 class="text-center mt-5 mb-2">Formulaire à remplir</h5>
    <h5 id="warning" class="text-center mb-5">Attention à bien compléter tous les champs avant de valider</h1>
    <div class="container text-center" id="form">
        <form action="update.php?productId=<?= $editProduct['id'] ?>" method="post" enctype="multipart/form-data" id="uploadForm">
            
            <div class="form-row mt-2">
                <div class="col-1">
                </div>
                <div class="col-2">
                    <label class="my-1 mr-2" for="Nb de personnes">Nb de personnes</label>
                    <select class="custom-select my-1 mr-sm-2" id="Nb de personnes" name="personne">
                        <option selected <?php if($editProduct['number'] === '1') echo "selected" ?>>1</option>
                        <option value="2" <?php if($editProduct['number'] === '2') echo "selected" ?>>2</option>
                        <option value="3" <?php if($editProduct['number'] === '3') echo "selected" ?>>3</option>
                        <option value="4" <?php if($editProduct['number'] === '4') echo "selected" ?>>4</option>
                        <option value="5" <?php if($editProduct['number'] === '5') echo "selected" ?>>5</option>
                        <option value="6" <?php if($editProduct['number'] === '6') echo "selected" ?>>6</option>
                        <option value="7" <?php if($editProduct['number'] === '7') echo "selected" ?>>7</option>
                        <option value="8" <?php if($editProduct['number'] === '8') echo "selected" ?>>8</option>
                        <option value="9" <?php if($editProduct['number'] === '9') echo "selected" ?>>9</option>
                        <option value="10" <?php if($editProduct['number'] === '10') echo "selected" ?>>10</option>
                        <option value="11" <?php if($editProduct['number'] === '11') echo "selected" ?>>11</option>
                        <option value="12" <?php if($editProduct['number'] === '12') echo "selected" ?>>12</option>                                                            
                    </select>
                </div>
                <div class="col-3">
                    <label for="mixture">Temps de préparation (en minutes)</label>
                    <input name="mixture" type="text" class="form-control" value="<?= $editProduct['mixture'] ?>">
                </div>
                <div class="col-3">
                    <label for="baking">Temps de cuisson (en minutes)</label>
                    <input name="baking" type="text" class="form-control" value="<?= $editProduct['baking'] ?>">
                </div>
                <div class="col-2 text-left ml-3">
                    <label name="categoryId" class="my-1 mr-2" for="Nb de personnes">Catégorie</label>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="categoryId" id="exampleRadios1" value="1" <?php if($editProduct['category_id'] === '1') echo "checked" ?>>
                        <label class="form-check-label" for="exampleRadios1"> Salée</label>
                    </div>
                    <div class="form-check">
                        <input class="form-check-input" type="radio" name="categoryId" id="exampleRadios2" value="2" <?php if($editProduct['category_id'] === '2') echo "checked" ?>>
                        <label class="form-check-label" for="exampleRadios2"> Sucrée</label>
                    </div>
                </div>
                <div class="col-1">
                </div>           
            </div>

            <div class="row mt-5">
                <div class="col-3">
                </div> 
                <div class="col-6 form-group">
                    <label for="nameRecipe">Nom de la recette</label>
                    <textarea name="nameRecipe" class="form-control" id="recette" rows="1"><?= $editProduct['name'] ?></textarea>
                </div>
                <div class="col-3">
                </div> 
            </div>
            <div class="row mt-5">
                <div class="col-12 form-group">
                    <label for="ingredients">Ingrédients</label>
                    <textarea name="ingredients" class="form-control" id="ingredients" rows="10"><?= $editProduct['ingredients'] ?></textarea>
                </div>


                <div class="col-12 form-group mt-3">
                    <label for="recipe">Recette</label>
                    <textarea name="recipe" class="form-control" id="Recette" rows="12"><?= $editProduct['recipe'] ?></textarea>
                </div>
            </div> 
            <div class="mt-4"> 
                <div class="custom-file">
                    <img class="mb-3" src="assets/img/<?= $editProduct['image'] ?>" width="150px">
                    <br>
                    <label for="file">Modifier mon image (jpeg ou png - 200Ko max)</label>
                    <input type="file" id="avatar" name="file" accept="image/png, image/jpeg">
             
             </div>        
                <div class="container text-center form-group signin mb-5 mt-5">
                    <button type="submit" class="btn btn-success text-uppercase send">Enregistrer les modifications</button>
                </div>
            </div>
        </form>
        <!-- créer une class invisibleBlock avec un display: None -->
        <div id="invisibleFormErrors" class="invisibleBlock">
            <!-- fond rouge, etc... -->
        </div>
    </div>
</section>


