<section>
    <?php if(isset($_SESSION['user'])): ?>   
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Vous êtes bien connecté(e) en tant que <strong><?php
                if (isset($_SESSION['user']))
                {
                    print($_SESSION['user']['firstname']);
                    print($_SESSION['user']['lastname']);
                } ?></strong>
                </div>
                <div class="col-sm-12 mt-3 mb-5 text-center">
                    <a href="disconnectProcess.php"><button class="btn btn-primary text-uppercase">Me déconnecter</button></a>    
                    <!-- /////// -->
                </div>
            </div>
        </div>
    <?php endif; ?> 
    
    <?php if(isset($userDisconnected) && $userDisconnected): ?>   
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Vous êtes bien déconnecté(e)
                </div>
            </div>
        </div>
    <?php endif; ?>

    <? if(isDataFromFormValid() == true): ?>   
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Merci pour votre inscription, vous pouvez désormais vous connecter en cliquant <a href="connection.php">ici</a>
                </div>
            </div>
        </div>
    <? endif; ?>
</section>
<section class="container"> 
    <div>        
        <div class="row">
            <div class="col-12 pt-5 pb-5 text-center">
                <div>
                    <h2>Ô Tartes</h2>
                    <h3>Découvrez les  meilleurs tartes salées et sucrées du moment. <br>Proposez votre recette fameuse et partagez là au plus grand nombre !
                    </h3>
                </div>
            </div>
        </div>
        <article class="row pb-5">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-4">
                <img src="assets/img/farine_otartes.jpg" alt="lorem ipsum" class="img-fluid">
            </div>
            <div class="col-sm-6">
                <p>
                    Nous sélectionnons et collectons pour vous les meilleures recettes de tartes salées et tarte sucrées.
                </p>
                <p>
                    Vous trouverez, tout au long de votre navigation, des infos sur les recettes, les ingrédients et les  petits plus pour préparer LA tarte qu'il vous faut.
                    N'hésitez pas également à partager vos recettes par <a href="#">ici</a>
                </p>
            </div>
            <div class="col-sm-1">
            </div>
        </article>
    </div>
    <div class="row homepage">
        <div class="col-12 text-center mb-5">
        <a href="#"><h4>Ô récentes Tartes!</h4></a>
        </div>
        <!-- < ?php foreach($recentProducts as $key => $recentProduct): ? > -->
        <?php foreach($recentProducts as $recentProduct): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card-recent.phtml');?>
            </div>
        <?php endforeach;?>

    </div>
    <div class="row homepage">
        <div class="col-12 text-center mb-5">
            <a href="#"><h4>Ô Tartes! salées</h4></a>
        </div>
        <?php foreach($saltedProducts as $saltedProduct): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card-3salty.phtml');?>
            </div>
        <?php endforeach;?>
    </div>
    <div class="row homepage">
        <div class="col-12 text-center mb-5">
            <a href="allSweetProducts.php?category_id=<?= $allSweetProducts['category_id'] ?>"><h4>Ô Tartes! sucrées</h4></a>        
        </div>
        <?php foreach($sweetProducts as $sweetProduct): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card-3sweet.phtml');?>
            </div>
        <?php endforeach;?>
    </div>
</section>