<section>
    <?php if(isset($_SESSION)): ?>   
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Vous êtes bien connecté(e) en tant que <strong><?php print($_SESSION['user']['firstname'])?> <?php print($_SESSION['user']['lastname']) ?></strong>
                </div>
            </div>
        </div>
    <?php endif; ?> 
    <? if(isDataFromFormValid() == true): ?>   
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Merci pour votre inscription, vous pouvez désormais vous connecter en cliquant <a href="connection.php">ici</a>
                </div>
            </div>
        </div>
    <? endif; ?>
</section>
<section class="container"> 
    <div>        
        <div class="row">
            <div class="col-12 pt-5 pb-5 text-center">
                <div>
                    <h2>Ô Tartes</h2>
                    <h3>Découvrez les  meilleurs tartes salées et sucrées du moment. <br>Proposez votre recette fameuse et partagez là au plus grand nombre !
                    </h3>
                </div>
            </div>
        </div>
        <article class="row pb-5">
            <div class="col-sm-1">
            </div>
            <div class="col-sm-4">
                <img src="assets/img/farine_otartes.jpg" alt="lorem ipsum" class="img-fluid">
            </div>
            <div class="col-sm-6">
                <p>
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Ducimus vero consectetur molestias id, dignissimos eveniet eum, labore ut illum quod perspiciatis odit qui eaque sequi magni! Velit sed similique quos.
                </p>
                <p>
                    Lorem ipsum, dolor sit amet consectetur adipisicing elit. Odio dolorum sapiente, asperiores blanditiis temporibus exercitationem. Optio quia fugiat maiores. Quod tempora optio ad voluptatum ducimus eum possimus vitae veritatis distinctio.
                </p>
            </div>
            <div class="col-sm-1">
            </div>
        </article>
    </div>
    <div class="row">
        <div class="col-12 text-center mb-5">
            <h4>Ô récentes Tartes!</h4>
        </div>
        <!-- < ?php foreach($recentProducts as $key => $recentProduct): ? > -->
        <?php foreach($recentProducts as $recentProduct): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card-recent.phtml');?>
            </div>
        <?php endforeach;?>

    </div>
    <div class="row">
        <div class="col-12 text-center mb-5">
            <h4>Ô Tartes! salées</h4>
        </div>
        <?php foreach($saltedProducts as $saltedProduct): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card-salty.phtml');?>
            </div>
        <?php endforeach;?>
    </div>
    <div class="row">
        <div class="col-12 text-center mb-5">
            <h4>Ô Tartes! sucrées</h4>
        </div>
        <?php foreach($sweetProducts as $sweetProduct): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card-sweet.phtml');?>
            </div>
        <?php endforeach;?>
    </div>
</section>