<section>
    <?php if($messageService->getMessage() === "user_disconnected"): ?>  
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Vous êtes bien déconnecté(e)
                </div>
            </div>
        </div>
    <?php endif; ?>

    <?php if($messageService->getMessage() === "user_created"): ?>   
        <div class="row">
            <div class="col-12 file-alert">
                <div class="alert alert-success text-center" role="alert">
                Merci pour votre inscription, vous pouvez désormais vous connecter <a href="connection.php"><button class="btn btn-primary text-uppercase">Me connecter</button></a>    
                </div>
            </div>
        </div>
    <?php endif; ?>
</section>

<section class="container">       
    <div class="row">
        <div class="col-12 mt-5 mb-5 text-center">
            <div>
                <h2>Ô Tartes&nbsp;!</h2>
                <h3>Découvrez les  meilleures tartes salées et sucrées du moment. <br>Proposez votre recette fameuse et partagez-la au plus grand nombre&nbsp;!
                </h3>
            </div>
        </div>
    </div>
    <article class="row pb-5">
        <div class="col-sm-1">
        </div>
        <div class="col-sm-4">
            <img src="assets/img/farine_otartes.jpg" alt="lorem ipsum" class="img-fluid">
        </div>
        <div class="col-sm-6">
            <ul>
                <li><p>Nous sélectionnons et collectons pour vous les meilleures recettes de tartes salées et tartes sucrées.</p></li>
                <li><p>Vous trouverez, tout au long de votre navigation, des infos sur les recettes, les ingrédients et les  petits plus pour préparer <br><strong>LA tarte</strong> qu'il vous faut.</p></li>
                <?php if(isset($_SESSION['user'])): ?>
                    <li><p>N'hésitez pas à partager vos recettes <a href="upload.php" class="btn btn-primary">Partager ma recette</a>
                <?php else: ?>                   
                    <li><p>N'hésitez pas à partager vos recettes <a href="shareRecipes.php" class="btn btn-primary">Partager ma recette</a>
                <?php endif; ?>              

            </ul>            
        </div>
        <div class="col-sm-1">
        </div>
    </article>

    <div class="row homepage">
        <div class="col-12 text-center mt-3">
            <h2>Ô récentes Tartes&nbsp;!</h2>
        </div>
    </div>
        <!-- < ?php foreach($recentProducts as $key => $recentProduct): ? > -->
    <div class="row">
        <?php foreach($recentProducts as $productForCard): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card.phtml');?>
            </div>
        <?php endforeach;?>
    </div>

    <div class="row homepage">
        <div class="col-12 text-center mb-3 mt-5" id="categ">
            <a href="allCategoryProducts.php?category_id=1"><h2>Ô Tartes&nbsp;! salées</h2></a>
        </div>
    </div>
    <div class="row"> 
        <?php foreach($saltedProducts as $productForCard): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card.phtml');?>
            </div>
        <?php endforeach;?>
    </div>

    <div class="row homepage">
        <div class="col-12 text-center mb-3 mt-5" id="categ">
            <a href="allCategoryProducts.php?category_id=2"><h2>Ô Tartes&nbsp;! sucrées</h2></a>        
        </div>
    </div>
    <div class="row">
        <?php foreach($sweetProducts as $productForCard): ?>
            <div class="col-md-4">
                <?php require('templates/pages/card.phtml');?>
            </div>
        <?php endforeach;?>
    </div>
    <div class="row mt-2 mb-5">
        <div class="col-4"></div>
        <div class="col-4 text-center">
            <a href="allProducts.php" class="btn btn-primary">Toutes nos Ô Tartes</a>
        </div>
        <div class="col-4"></div>
    </div>
</section>