<section class="bloc-intro">
    <div class="container">
        <div class="row">
            <div class="col-12 mt-5 mb-5 text-center">
                <h2>Vous voulez déguster une délicieuse tarte ? <br>Voici une sélection des meilleures tartes salées et sucrées de France...</h2>
            </div>
        </div>
        <!-- LIGNE 1 -->
        <div class="row">
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="https://www.gourmand-croquant.com/fr/patisseries/12-tarte-citron.html" target="_blank">
                    <h2>Tarte au citron de Cyril Lignac</h2>
                    <div>

                        <img src="assets/img/media/tarte_citron_lignac.png" alt="La sublime et délicieuse tarte au citron de Cyril Lignac" class="img-responsive fit-image">
                    </div>
                </a>
            </div>
            <div class="col-2 mt-5 mb-5 text-center">
            </div>
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="http://www.leparisien.fr/val-d-oise-95/saint-ouen-l-aumone-il-fait-la-meilleure-tarte-aux-pommes-d-ile-de-france-03-11-2019-8185461.php" target="_blank">
                    <h2>La succulente tarte aux pommes de Jérémy Joaquim </h2>
                    <img src="assets/img/media/tarte_pommes_JJoaquim.png" alt="Tarte aux fraises de Sébastien Degardin, aussi bon à l'oeil qu'au goût" class="img-responsive fit-image">
                </a>
            </div>

        </div>
        <!-- LIGNE 2 -->
        <div class="row">
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="https://www.lareinedestartes.com/" target="_blank">
                    <h2>Au restaurant LA REINE DES TARTES</h2>
                    <img src="assets/img/media/reine_des_tartes.png" alt="La sublime et délicieuse tarte au citron de Cyril Lignac" class="img-responsive fit-image">
                </a>
            </div>
            <div class="col-2 mt-5 mb-5 text-center">

            </div>
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="http://www.sebastien-degardin.com/presse/" target="_blank">
                    <h2>Tarte aux fraises de Sébastien Degardin</h2>
                    <img src="assets/img/media/tarte_fraises_Dejardin.png" alt="Tarte aux fraises de Sébastien Degardin, aussi bon à l'oeil qu'au goût" class="img-responsive fit-image">
                </a>
            </div>
        </div>
        <!-- LIGNE 3 -->
        <div class="row">
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="http://www.lalosparis.com/nos-patisseries/" target="_blank">
                    <h2>Les tartes du Meilleur Ouvrier de France Frédéric Lalos</h2>
                    <img src="assets/img/media/tarte_Lalos.png" alt="La sublime et délicieuse tarte au citron de Cyril Lignac" class="img-responsive fit-image">
                </a>            
            </div>
            <div class="col-2 mt-5 mb-5 text-center">

            </div>
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="https://www.elle.fr/Loisirs/Sorties/Restaurants/brunch-paris/Tartes-Kluger" target="_blank">
                    <h2>Les tartes de chez Kluger</h2>
                    <img src="assets/img/media/tartes_Kluger.png" alt="Tarte aux fraises de Sébastien Degardin, aussi bon à l'oeil qu'au goût" class="img-responsive fit-image">
                </a>      
            </div>
        </div>
        <!-- LIGNE 4 -->
        <div class="row">
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="https://stohrer.fr/" target="_blank">
                    <h2>La tarte tatin de Stohre</h2>
                    <img src="assets/img/media/tarte_tatin_Stohre.png" alt="La sublime et délicieuse tarte au citron de Cyril Lignac" class="img-responsive fit-image">
                </a>      
            </div>
            <div class="col-2 mt-5 mb-5 text-center">

            </div>
            <div class="col-5 mt-5 mb-5 text-center media">
                <a href="http://tartes-chez-moi.fr/" target="_blank">
                    <h2>Au restaurant TARTES CHEZ MOI</h2>
                    <img src="assets/img/media/tartes_chez_moi.png" alt="Tarte aux fraises de Sébastien Degardin, aussi bon à l'oeil qu'au goût" class="img-responsive fit-image media4">
                </a>  
            </div>
        </div>
    </div>
</section>