<section class="bloc-intro">
    <div class="container">
        <div class="row text-center">
            <div class="oneProduct col-12">
                <h2 class="mt-5"><?=$oneProduct['name']?></h2>
                <?php if(isset($oneProduct['user_id']) && ($oneProduct['user_id'] !== '0')): ?>
                    <div class="memberProduct mb-5" >            
                        <h3>Recette partagée par 
                            <a href="allProductsOneMember.php?memberId=<?= $oneUser['id'] ?>">
                            <?php foreach($allUsers as $user)
                            {if ($user['id'] === $oneProduct['user_id']) {
                                print($user['firstname'] . ' '. $user['lastname']);
                                break;
                            }} ?> 
                            </a>
                        </h3>
                    </div>
                <?php endif;?>

            </div>
        </div>
        <div class="row">
            <div class="col-6">
                <div class="row">
                    <div class="col-4">
                    </div>
                    <div class="col-7">
                        <ul>
                            <li><p class="">Nombre de personnes : <?=$oneProduct['number']?></p></li>
                            <li><p class="">Temps de préparation : <?=$oneProduct['mixture']?></p></li>
                            <li><p class="">Temps de cuisson : <?=$oneProduct['baking']?></p></li>
                        </ul>
                    </div>
                    <div class="col-1">
                    </div>
                </div>                
            </div> 
            <div class="col-6 text-center">
                <img src="assets/img/<?=$oneProduct['image']?>" alt="<?=$oneProduct['alt']?>" class="img-responsive fit-image" width="500">
            </div> 
        </div>     
    </div>
</section>
<section>
    <div class="container">
        <div class="row mt-5">
            <div class="col-lg-4">
                <div class="">
                    <h2 class="mb-3 text-uppercase"><span>Ingrédients</span></h2>  
                    <ul><?=$oneProduct['ingredients']?><br></ul>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="recette">
                <h2 class="mb-3 text-uppercase"><span>Recette</span></h2> 
                    <ul><?=$oneProduct['recipe']?></ul>   
                </div>
            </div>
        </div>
        <div class="row mt-5 mb-5">
            <div class="col-4 text-center">
                <a href="index.php" class="btn btn-primary">Retour Accueil</a>
            </div>
            <div class="col-4 text-center">
                <a href="allCategoryProducts.php?category_id=1" class="btn btn-primary">Toutes nos Ô Tartes salées</a>
            </div>
            <div class="col-4 text-center">
                <a href="allCategoryProducts.php?category_id=2" class="btn btn-primary">Toutes nos Ô Tartes sucrées</a>
            </div>
        </div>
    </div>
</section>
