<section class="bloc-intro">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 mt-5 mb-5 text-center">
                <h1>Inscription</h1>
            </div>
        </div>
    </div>
</section>
<section >
    <div class="container text-center" id="form">
        <div class="row">
            <div class="col-sm-12 text-center">
                <div class="row">
                    <div class="col-sm-2 text-center">
                    </div>

                    <div class="col-sm-8 text-center">
                        <form action="signUpProcess.php" method="post">
                            <div class="form-group">
                                <input type="text" class="form-control" id="lastname" name="lastname" placeholder="Nom">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" id="firstname" name="firstname" placeholder="Prenom">
                            </div>            
                            <div class="form-group">
                                <input type="email" class="form-control" id="email" name="email" aria-describedby="emailHelp" placeholder="Adresse email*" required>
                                <small id="emailHelp" class="form-text text-muted">Ce champ est obligatoire</small>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe*" required>
                                <small id="emailHelp" class="form-text text-muted">Champ est obligatoire, 6 caractères minimum.</small>
                            </div>
                            <div class="form-group pt-3">
                                <button type="submit" class="btn btn-success text-uppercase">Se connecter</button>
                            </div>
                        </form>
                    </div>
                    <div class="col-sm-2 text-center">
                    </div>
                </div>
            </div>
            <div class="col-sm-12 mt-3 mb-3 text-center">
                <a href="index.php"><button class="btn btn-primary text-uppercase">accueil</button></a>    
            </div>
        </div>
    </div>
</section>

