<section class="message">
    <div class="alert alert-success text-center" role="alert">
    Votre recette a bien été enregistrée.
    </div>
</section>

<section class="container upload">
  
    <div id="recap" class="row">
        <div class="col-lg-4">
        </div>
        <div id="recapborder" class="col-lg-4">
            <div class="file-text">
                <h2 class="text-uppercase mb-3">Récapitulatif</h2>
                <h4>Nom du fichier&nbsp;: <span><?=$fileName?></span></h4>
                <h4>Type&nbsp;: <span><?=$fileType?></span></h4>
                <h4>Taille&nbsp;: <span><?=$fileSize?> ko</span></h4>
                <h4>Enregistré sous&nbsp;: <span><?=$filePath?></span> </h4>
            </div>
        </div>
        <div class="col-lg-4">
        </div>
    </div>
    <div class="row mt-2 mb-5">
            <div class="col-3"></div>
            <div class="col-3 text-center">
                <a href="upload.php" class="btn btn-primary">Ajouter une autre recette</a>
            </div>
            <div class="col-3">
                <a href="member.php?memberId=<?= $_SESSION['user']['id'] ?>" class="btn btn-primary">Voir mes recettes</a>
            </div>
            <div class="col-3"></div>
        </div>
</section>
