<section class="message">
    <div class="alert alert-success text-center" role="alert">
    Votre recette a bien été enregistrée.
    </div>
</section>

<section class="container upload">
  
    <div id="recap" class="row">
        <div class="col-lg-4">
        </div>
        <div id="recapborder" class="col-lg-4">
            <div class="file-text">
                <h2 class="text-uppercase mb-3">Récapitulatif</h2>
                <h4>Nom du fichier&nbsp;: <span><?=$fileName?></span></h4>
                <h4>Type&nbsp;: <span><?=$fileType?></span></h4>
                <h4>Taille&nbsp;: <span><?=$fileSize?> ko</span></h4>
                <h4>Enregistré sous&nbsp;: <span><?=$filePath?></span> </h4>
            </div>
        </div>
        <div class="col-lg-4">
        </div>
    </div>
</section>
