        </main>
        <footer>
            <div class="container">
                <div class="row">
                    <div class="col-12 text-center">
                        <ul class="contact in-line-blocks">
                            <li>@Claire Brosset</li>
                            <li class="horiz"><a href="https://github.com/ClaireFBWCE" target="_blank"><i class="fab fa-github"></i> Blog</a></li>
                            <li class="horiz"><a href="https://www.linkedin.com/in/clairebrossetcammarata/" target="_blank"><i class="fab fa-linkedin"></i> About me</a>
                            </li>
                        </ul>
                        <h6></h6>
                    </div>
                </div>
            </div>
        </footer>        
    </body>
</html>