<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ô Tartes - recettes de tartes salées et sucrées</title>
    <link rel="icon" type="image/png" href="assets\img\picto-pie.png">
    <link rel="shortcut icon" href="assets\img\picto-pie.png">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" >
    <link rel="stylesheet" href="assets\css\reset.css">
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="assets\css\bootstrap.css">
    <link rel="stylesheet" href="assets\css\styles.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-dark static-top">
            <div class="container">
                <a class="navbar-brand" href="index.php">
                    <img class="logo" src="assets/img/picto-pie.png" alt="" height="60">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="index.php">Accueil</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="allCategoryProducts.php?category_id=1">Salée</a>
                        </li>
                        <li class="nav-item">
                            <!-- <a class="nav-link" href="allSweetProducts.php">Sucré</a> -->
                            <a class="nav-link" href="allCategoryProducts.php?category_id=2">Sucrée</a>
                            <!-- <a href="oneProduct.php?id=<c?= $sweetProduct['id'] ?>">     
                               
                            url ==> localhost/o-tartes/allSweetProducts.php?category_id=2
                            -->

                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">Media</a>
                        </li>
                        <!-- <li class="nav-item">
                            < ?php if(!$userConnection):?>
                                <a class="nav-link text-white" href="connection.php"><img src="assets/img/signin3.png" alt="Ô Tartes ! se connecter" width="50"></a>
                            < ?php else: ?>
                                <a class="nav-link" href="signUp.php"><img src="assets/img/signout4.png" alt="Ô Tartes ! se déconnecter" width="50"></a>
                            < ?php endif;?>
                        </li>     -->
                        <li class="nav-item connect">
                        <a class="nav-link" href="connectionProcess.php"><img src="assets/img/signin3.png" alt="Connexion"></a>
                        </li>   
                        <!-- <li class="nav-item">
                            <a class="nav-link" href="signUpProcess.php">Inscription</a>
                        </li>                 -->
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container mt-5 pt-5 text-center">
            <h1><?= $title ?></h1>
            <?php if($title == 'Bienvenue sur Ô Tartes !'): ?>
                <h2>Votre bonheur en tartes salées ou sucrées!</h2>
            <?php endif; ?>
        </div>
    </header>
    <main>